-- Run with LocomotionRules passed in; no Roblox services are required.
return function(Rules)
    local count = 0
    local function input(overrides)
        local result = {alive=true, held=true, grounded=true, moving=true, forward=true,
            speed=0, normalSpeed=10, aimSpeed=5, sprintSpeed=18}
        for key, value in pairs(overrides or {}) do result[key] = value end
        return result
    end
    local function check(name, callback)
        callback()
        count = count + 1
    end
    check("sprint ramps to full speed", function()
        local state = Rules.New()
        local early = Rules.Step(state,input(),0.1)
        assert(early.speed > 10 and early.speed < 18 and not early.sprinting)
        local full = Rules.Step(state,input(),2)
        assert(full.speed == 18 and full.sprinting)
    end)
    check("release restores walking speed", function()
        local state = Rules.New()
        Rules.Step(state,input(),2)
        local result = Rules.Step(state,input({held=false}),0.01)
        assert(result.speed == 10 and not result.sprinting and result.sprintProgress == 0)
    end)
    check("holding Shift before ADS switches sprint into focus", function()
        local state = Rules.New()
        Rules.Step(state,input(),2)
        local result = Rules.Step(state,input({aiming=true}),0.01)
        assert(result.speed == 5 and not result.sprinting and result.inhaled and result.holding)
        result = Rules.Step(state,input({aiming=true}),0.4)
        assert(result.focusProgress == 1 and not result.inhaled)
    end)
    check("pressing Shift after ADS focuses", function()
        local state = Rules.New()
        assert(not Rules.Step(state,input({held=false,aiming=true}),0.1).holding)
        assert(Rules.Step(state,input({aiming=true}),0.1).inhaled)
    end)
    check("minimum focus time then one exhale on release", function()
        local state = Rules.New()
        Rules.Step(state,input({aiming=true}),0.01)
        assert(Rules.Step(state,input({aiming=true,held=false}),0.1).holding)
        local result = Rules.Step(state,input({aiming=true,held=false}),0.3)
        assert(not result.holding and result.exhaled)
        assert(not Rules.Step(state,input({aiming=true,held=false}),0.1).exhaled)
    end)
    check("focus resumes after cooldown while Shift stays held", function()
        local state = Rules.New()
        Rules.Step(state,input({aiming=true}),0)
        assert(Rules.Step(state,input({aiming=true}),5.6).exhaled)
        assert(not Rules.Step(state,input({aiming=true}),1).holding)
        assert(Rules.Step(state,input({aiming=true}),1.6).inhaled)
    end)
    check("movement prevents focus and stopping permits it", function()
        local state = Rules.New()
        assert(not Rules.Step(state,input({aiming=true,speed=3}),0.1).holding)
        assert(Rules.Step(state,input({aiming=true,speed=2.9}),0.1).holding)
        assert(Rules.Step(state,input({aiming=true,speed=4}),0.4).exhaled)
    end)
    check("ADS exit resumes held sprint", function()
        local state = Rules.New()
        Rules.Step(state,input({aiming=true}),0)
        local result = Rules.Step(state,input(),0.4)
        assert(result.accelerating and not result.holding and result.exhaled)
    end)
    check("restrictions prevent sprint", function()
        for _, restriction in ipairs({"menu","blocked","crouching","climbing","vaulting","mounted"}) do
            local state = Rules.New()
            local result = Rules.Step(state,input({[restriction]=true}),3)
            assert(not result.accelerating and result.sprintProgress == 0, restriction)
        end
    end)
    check("direction follows camera mode", function()
        assert(not Rules.Step(Rules.New(),input({forward=false}),3).sprinting)
        assert(Rules.Step(Rules.New(),input({forward=false,freeLook=true}),3).sprinting)
    end)
    check("toggle sprint persists after release and toggles off", function()
        local state = Rules.New()
        Rules.Step(state,input({toggle=true}),2)
        assert(Rules.Step(state,input({toggle=true,held=false}),0.1).sprinting)
        assert(not Rules.Step(state,input({toggle=true}),0.1).accelerating)
    end)
    check("instant perks and speed multipliers apply", function()
        local result = Rules.Step(Rules.New(),input({instant=true,sprintSpeed=27,normalSpeed=15}),0)
        assert(result.speed == 27 and result.sprinting)
    end)
    check("jump grace expires then landing resumes", function()
        local state = Rules.New()
        assert(Rules.Step(state,input({grounded=false}),0.1).accelerating)
        assert(not Rules.Step(state,input({grounded=false}),0.3).accelerating)
        assert(Rules.Step(state,input(),0.1).accelerating)
    end)
    check("death and respawn cannot inherit focus or cooldown", function()
        local state = Rules.New()
        Rules.Step(state,input({aiming=true}),0)
        local dead = Rules.Step(state,input({alive=false,aiming=true}),0.4)
        assert(not dead.holding and not dead.sprinting)
        assert(Rules.Step(Rules.New(),input({aiming=true}),0).inhaled)
    end)
    return count
end
