return {
	["Settings Data"] = {
		["Performance"] = {
			["WeaponSkins"] = {
				DisplayName = "Hide Weapon Skins",
				Current = false,
				Base = false,
			},
			
			["Graphics/FX"] = {
				DisplayName = "Reduced Graphics and FX",
				DisplayText = "Reduces many performance intensive effectsas well as Terrain Materials",
				Current = false,
				Base = false,
			},
			
			["WeaponEffects"] = {
				DisplayName = "Reduced Graphics and FX",
				DisplayText = "Disables moving parts on other players' weapons, helping performance when a lot of gunfire is involved.",
				Current = false,
				Base = false,
			},
			
			["GibEffects"] = {
				DisplayName = "Reduced Graphics and FX",
				Current = false,
				Base = false,
			},
			
			["BulletTrail"] = {
				DisplayName = "Disable Bullet Trail Effects",
				Current = false,
				Base = false,
			},
			
			["BloodCharacters"] = {
				DisplayName = "Disable Blood and Dirt on Characters",
				Current = false,
				Base = false,
			},
			
			["FloorBlood"] = {
				DisplayName = "Disable Floor Blood",
				Current = false,
				Base = false,
			},
		},
		
		["Quality of Life"] = {
			["ToggleSprint"] = {
				DisplayName = "Toggle Sprint",
				Current = false,
				Base = false,
			},
			
			["ToggleAim"] = {
				DisplayName = "Toggle Aim",
				Current = false,
				Base = false,
			},
			
			["HelmetAccessories"] = {
				DisplayName = "Use no Masks/Scarves with No Helmets",
				DisplayText = "When selecting No Helmets, it will remove the class related accessories e.g Moriticians, Rooks Mask aswell as any benefit from them.",
				Current = false,
				Base = false,
			},
			
			["FirearmVolume"] = {
				DisplayName = "Reduce Firearm Volume",
				Current = false,
				Base = false,
			},
			
			["AltPrimeKnellHammer"] = {
				DisplayName = "Use [Alt] to Prime Knell Hammer",
				DisplayText = "By default, [@ALT] toggles between priming on click or not, this setting will make it so pressing [@ALT] on its own will just prime the hammer directly",
				Current = false,
				Base = false,
			},
			
			["WhisperAutoLoader"] = {
				DisplayName = "Start with Auto-Loader equipped for 'Whisper' Silenced Rifle",
				Current = false,
				Base = false,
			},
			
			["OldMortSelection"] = {
				DisplayName = "Use Old Mortician Stim Selection",
				Current = false,
				Base = false,
			},
			
			["OldShockKitSelection"] = {
				DisplayName = "Old Shock Kit selection order",
				Current = false,
				Base = false,
			},
			
			["MuteMusic"] = {
				DisplayName = "Mute Music",
				Current = false,
				Base = false,
			},
			
			["DreadNoughtShockTrooperSkip"] = {
				DisplayName = "Skip Dradnought Selection as Shock Trooper",
				DisplayText = "When being selected for Dreadnought, if you are a Shock Trooper, it will instead skip you and pass it onto the next player",
				Current = false,
				Base = false,
			},
			
			["OptOutEliteReinSel"] = {
				DisplayName = "Opt Out of Elite Reinforcement Selection",
				DisplayText = "Shock Trooper Crates will automatically give you the kit matching toyour class, rather than giving you a menu pop up.",
				Current = false,
				Base = false,
			},
			
			["AutoShock"] = {
				DisplayName = "Enable automatic Class related Shock Trooper Selection",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["OptOutDreadnought"] = {
				DisplayName = "Opt out of Dreadnought Selection",
				Current = false,
				Base = false,
			},
			
			["DisableDeathRattles"] = {
				DisplayName = "DisableBrutalDeathRattles",
				Current = false,
				Base = false,
			},
			
			["DisableBodyShooting"] = {
				DisplayName = "Disable Body Shooting",
				DisplayText = "Bullets by default can hit dead bodies, knocking them around in rare scenes these might interfere with shooting at enemies, this setting disables that.",
				Current = false,
				Base = false,
			},
			
			["DisableAmbdiSwapReload"] = {
				DisplayName = "Disable Ambidextrous Swap Reloading",
				DisplayText = "When Reloading with Ambidextrous, you will swap to the other weapon and reload it before swapping back, this disables that to give you full control over which guns you want to reload",
				Current = false,
				Base = false,
			},
			
			["DisableTranHeavyLance"] = {
				DisplayName = "Disable Transparent Heavy Lance",
				DisplayText = "By default, when using the Heavy Lance as Lancer, the lance will be permanently transparent at all times, making it far less visible. This setting makes it always visible.",
				Current = false,
				Base = false,
			},
		},
		
		["Immersion"] = {
			["UntranslatedVoiceComms"] = {
				DisplayName = "Enable Untranslated Voice Commands",
				DisplayText = "Voice commnds will be presented in that players set language, rather then the selected game language",
				Current = false,
				Base = false,
			},
			
			["HideCrosshair"] = {
				DisplayName = "Hide Crosshair",
				Current = false,
				Base = false,
			},
			
			["HideTeammateClassIcons"] = {
				DisplayName = "Hide Teammate Class Icons",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["DisableObstructedBarrelMuzzle"] = {
				DisplayName = "Disable Indicator showing Obstructed Barrel",
				Current = false,
				Base = false,
			},
			
			["DisableInteractHighlight"] = {
				DisplayName = "Disable Interactable Highlight",
				Current = false,
				Base = false,
			},
			
			["Disable Trap and Construct Highlighting"] = {
				DisplayName = "Disable Trap and Construct Highlighting",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["DisableHairs"] = {
				DisplayName = "Disable Hairs on Players",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["AutomaticFirstPerson"] = {
				DisplayName = "Automatic First Person when Respawning",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
		},
		
		["UI & Visuals"] = {
			["TransCrosshair"] = {
				DisplayName = "Enable Transparent Crosshair",
				Current = false,
				Base = false,
			},
			
			["StaticCrosshair"] = {
				DisplayName = "Enable Static Crosshair (Replaces Default Crosshair)",
				Current = false,
				Base = false,
			},
			
			["MuteOfficerPings"] = {
				DisplayName = "Mute other Officer Pings",
				Current = false,
				Base = false,
			},
			
			["ExtendBarrelOb"] = {
				DisplayName = "Extend Barrel Obstruction Indictator distance considerably",
				Current = false,
				Base = false,
			},
			
			["RequestPopUpsHide"] = {
				DisplayName = "Hide Request pop-ups from Allies",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["HideGameModeBrief"] = {
				DisplayName = "Hide Gamemode Brief on First Spawn",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["HideDistantTeammateIcons"] = {
				DisplayName = "Hide Distant Teammate Class Icons",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["HideChat"] = {
				DisplayName = "Hide in-game Chat",
				Current = false,
				Base = false,
			},
			
			["DisplayVolkPhysicalScope"] = {
				DisplayName = "Disable Physical Scope for the 'Volk' Scoped Rifle",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["HideHintPopups"] = {
				DisplayName = "Disable Hint Pop-Ups",
				Current = false,
				Base = false,
			},
			
			["HideDangerPings"] = {
				DisplayName = "Disable Danger Pings",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			},
			
			["HideBloodSmear"] = {
				DisplayName = "Disable Blood Smearing on Screen",
				DisplayText = "Temp",
				Current = false,
				Base = false,
			}
		},
		
		["Inputs"] = {
			["Sensitivities"] = {
				["Aiming Sensitivity"] = 1,
				["Scoped Sensitivity"] = 0.4
			},
			
			["Binds"] = {
				["Alternate Action"] = {
					Default = "Q",
					Current = "Q",
				},
			
				["Check Ammo"] = {
					Default = "T",
					Current = "T",
				},
				
				["Special Action"] = {
					Default = "T",
					Current = "T",
				},
				
				["Wipe Face"] = {
					Default = "Z",
					Current = "Z",
				},
				
				["Crouch"] = {
					Default = "C",
					Current = "C",
				},
				
				["Emergency Reload Drop"] = {
					Default = "T",
					Current = "T",
				},
				
				["Class Equipment"] = {
					Default = "G",
					Current = "G",
				},
				
				["First Person"] = {
					Default = "V",
					Current = "V",
				},
				
				["Flip Camera"] = {
					Default = "F",
					Current = "F",
				},
				
				["Hide Hud"] = {
					Default = "P",
					Current = "P",
				},
				
				["Menu"] = {
					Default = "M",
					Current = "M",
				},
				
				["Sprint"] = {
					Default = "LeftShift",
					Current = "LeftShift",
				},
				
				["Player List"] = {
					Default = "Tab",
					Current = "Tab",
				},
				
				["Reload"] = {
					Default = "R",
					Current = "R",
				},
				
				["Extra Action"] = {
					Default = "R",
					Current = "R",
				},
				
				["Reset Character"] = {
					Default = "Backspace",
					Current = "Backspace",
				},
				
				["Shift Lock"] = {
					Default = "LeftControl",
					Current = "LeftControl",
				},
				
				["Spectate Left"] = {
					Default = "Q",
					Current = "Q",
				},
				
				["Spectate Right"] = {
					Default = "E",
					Current = "E",
				},
				
				["Swap Team"] = {
					Default = "B",
					Current = "B",
				},
				
				["Surrender"] = {
					Default = "B",
					Current = "B",
				},
				
				["View Objectives"] = {
					Default = "X",
					Current = "X",
				},
				
				["Objectives Tool"] = {
					Default = "X",
					Current = "X",
				},
				
				["Voice Lines"] = {
					Default = "X",
					Current = "X",
				},
				
				["Voice Command: Request Ammo"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Voice Command: Danger There"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Voice Command: Request Medic"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Voice Command: Need Support"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Officer Command: Defend Here"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Officer Command: Follow Me"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Officer Command: Compound Order"] = {
					Default = "None",
					Current  = "None",
				},
				
				["Voice Command: Thank You"] = {
					Default = "None",
					Current  = "None",
				},
			}
		}
	},

	["PlayerData"] = {
		["CMDRLevel"] = 5,
		
		["Unlocked Items"] = {
			["PrinceRifle"] = true,
			["GraceRevolver"] = true,
			["CrestfallRifle"] = true,
			["JudgementRifle"] = true,
			["VolkRifle"] = true,
		},
		
		["Equipment"] = {
			["Primary"] = "PrinceRifle",
			["Secondary"] = "GraceRevolver",
			["Perks"] = {},
		}
	},
}
