return {
	["Settings Data"] = {
		["Graphical Options"] = {

		},

		["Miscellanous Options"] = {

		},

		["Input Options"] = { 
			["Free Look"] = "Enum.KeyCode.LeftControl",
			["Shoulder Switch"] = "Enum.KeyCode.F",
			["First Person"] = "Enum.KeyCode.V",
			["Sprint"] = "Enum.KeyCode.LeftShift",
			["Crouch"] = "Enum.KeyCode.C",
			["Emergency Drop"] = "Enum.KeyCode.T"
		},
	},

	["PlayerData"] = {
		["CMDRLevel"] = 5,
		
		["Unlocked Items"] = {
			["PrinceRifle"] = true,
			["GraceRevolver"] = true,
		},
		
		["Equipment"] = {
			["Primary"] = "PrinceRifle",
			["Secondary"] = "GraceRevolver",
			["Perks"] = {},
		}
	},
}