return {
	[2756349779] = true, -- // Praxitos,
	[1953037778] = true, -- // Novatality,


	[93664655] = true, -- // AuroreanNomad,
	[1690823524] = true, -- // L4ncified,
	[100617991] = true, -- // LuGamer011,
	[404454192] = true, -- // criptinac,
	[66934974] = true, -- // sploinkst,
	[34366405] = true, -- // aduremaister,

	[3800497291] = true, -- // BruhBot8707,
	[98677788] = true, -- // EndetX3,
	[5648718529] = true, -- // Kat_TunnelDog

}
-- nova the comma has to be after the true, not at the end